spring.application.name=MS Exam User
spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# Configuración JWT
app.jwt.secret=mi_clave_super_secreta
app.jwt.expirationMs=86400000

# Regex de validación
app.email.regex=^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$
app.password.regex=^(?=.{8,}$)(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).*$


# Swagger: disponible en /swagger-ui.html o /swagger-ui/index.html


# For logging h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
